services:
  nodejs-server:
    image: node:alpine
    container_name: cuisine-connect-node-server
    working_dir: /home/app
    tty: true
    stdin_open: true
    user: node
    volumes:
      - ./:/home/app
    ports:
      - 3000:3000
    networks:
      - cuisine-connect-network

networks:
  cuisine-connect-network:
